# TODO: Keep until we still use `decorator-transforms.patch`
packages:
  - 'packages/*'
approveBuilds: esbuild

autoInstallPeers: false
patchedDependencies:
  decorator-transforms: patches/decorator-transforms.patch
resolvePeersFromWorkspaceRoot: false
